### PR TITLE
Truly graceful shutdown

### PR DESCRIPTION
**Pull request by kachayev**
The rest of the #365 story. The key idea and the flow are described in comments.

There're still a few things I need to add/check:
* [done] tests
* [done] documentation
* [done] `shutdown-gracefully` with 1-arity
* [done] fix/rethink the problem with executor being shutdown earlier

Sharing this to get early feedback as it got quite complex and there're a few design choices that are not obvious/intuitive.

### CODE REVIEW

**Comment by kachayev** [comment]
@ztellman This one is also ready to be reviewed.

What do we have here?

1. `netty/graceful-shutdown` with a few timing options, returns deferred that yield when shutting down is finished or timed out.

2. `on-shutdown` parameter for a new websocket connection (server) to be notified about the server being shutting down to clean up properly. 

3. `netty/ConnectionManager` protocol, `netty/noop-connections-manager` that does not track anything (used for TCP servers and as an option for those whose main concern is performance).

4. Connection hijacking mechanism (using event triggering through the pipeline) to mark that the connection should be managed manually, not automatically (used for WebSockets and left as "public" API for any other use cases, e.g. long-polling, files transfer etc). 

There're quite a few changes here... would love to hear a feedback :)

**Comment by ztellman** [comment]
Thanks for your work on this, I'm going to have to take some time to review it.

**Comment by kachayev** [comment]
@ztellman Sure, this one is kinda tricky 😑Let me also fix those merge conflict here.

**Comment by kachayev** [comment]
Updated.

**Comment by petterik** [comment]
I just tested out the `ft-gracefull-shutdown` branch and it made my tests pass.

My tests wouldn't pass by using `(.close server) (netty/await-for-close)` from aleph `0.4.6` nor `0.4.7-alpha2`. Was also seeing the exceptions mentioned in #365

**Comment by kachayev** [comment]
@ztellman Updated to resolve conflicts with the latest introduced `:manual-ssl?` option

**Comment by kachayev** [comment]
@petterik Your tests fail specifically because of `java.lang.ClassNotFoundException`, right? Or is there something else?

**Comment by petterik** [comment]
@kachayev: These are the errors I'm getting `[aleph "0.4.6"]` and `[aleph "0.4.7-aleph2"]`:

```
18-10-30 19:45:03 periksson-mac.local WARN [io.netty.util.concurrent.DefaultPromise:151] - An exception was thrown by aleph.netty$wrap_future$reify__49615.operationComplete()
                                                      java.lang.Thread.run                         Thread.java: 748
                      io.netty.util.concurrent.FastThreadLocalRunnable.run        FastThreadLocalRunnable.java:  30
               io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run            GlobalEventExecutor.java: 248
                             io.netty.util.concurrent.DefaultPromise$1.run                 DefaultPromise.java: 435
                        io.netty.util.concurrent.DefaultPromise.access$000                 DefaultPromise.java:  33
                io.netty.util.concurrent.DefaultPromise.notifyListenersNow                 DefaultPromise.java: 485
                   io.netty.util.concurrent.DefaultPromise.notifyListener0                 DefaultPromise.java: 511
io.netty.util.concurrent.MultithreadEventExecutorGroup$1.operationComplete  MultithreadEventExecutorGroup.java: 117
                        io.netty.util.concurrent.DefaultPromise.setSuccess                 DefaultPromise.java:  94
                   io.netty.util.concurrent.DefaultPromise.notifyListeners                 DefaultPromise.java: 424
                io.netty.util.concurrent.DefaultPromise.notifyListenersNow                 DefaultPromise.java: 485
                   io.netty.util.concurrent.DefaultPromise.notifyListener0                 DefaultPromise.java: 511
                           aleph.netty/wrap-future/reify/operationComplete                           netty.clj: 199
                                                manifold.deferred/success!                        deferred.clj: 243
                                        manifold.deferred.Deferred/success                        deferred.clj: 398
                                    manifold.deferred.Deferred/fn/<clinit>                        deferred.clj: 398
                                                                       ...
                                                   java.lang.Class.forName                          Class.java: 348
                                                  java.lang.Class.forName0                           Class.java
     java.lang.ClassNotFoundException: clojure/lang/PersistentArrayMap
java.lang.ExceptionInInitializerError:
```

```
18-10-30 19:45:14 periksson-mac.local WARN [io.netty.util.concurrent.DefaultPromise:151] - An exception was thrown by aleph.netty$wrap_future$reify__49615.operationComplete()
                                                      java.lang.Thread.run                         Thread.java: 748
                      io.netty.util.concurrent.FastThreadLocalRunnable.run        FastThreadLocalRunnable.java:  30
               io.netty.util.concurrent.GlobalEventExecutor$TaskRunner.run            GlobalEventExecutor.java: 248
                             io.netty.util.concurrent.DefaultPromise$1.run                 DefaultPromise.java: 435
                        io.netty.util.concurrent.DefaultPromise.access$000                 DefaultPromise.java:  33
                io.netty.util.concurrent.DefaultPromise.notifyListenersNow                 DefaultPromise.java: 485
                   io.netty.util.concurrent.DefaultPromise.notifyListener0                 DefaultPromise.java: 511
io.netty.util.concurrent.MultithreadEventExecutorGroup$1.operationComplete  MultithreadEventExecutorGroup.java: 117
                        io.netty.util.concurrent.DefaultPromise.setSuccess                 DefaultPromise.java:  94
                   io.netty.util.concurrent.DefaultPromise.notifyListeners                 DefaultPromise.java: 424
                io.netty.util.concurrent.DefaultPromise.notifyListenersNow                 DefaultPromise.java: 485
                   io.netty.util.concurrent.DefaultPromise.notifyListener0                 DefaultPromise.java: 511
                           aleph.netty/wrap-future/reify/operationComplete                           netty.clj: 199
                                                manifold.deferred/success!                        deferred.clj: 243
                                        manifold.deferred.Deferred/success                        deferred.clj: 398
java.lang.NoClassDefFoundError: Could not initialize class manifold.deferred.Deferred$fn__46265
```

**Comment by kachayev** [comment]
@petterik Oh, yeah. Those are the same we've discussed in #365. I didn't find any specific reason for `ClassNotFoundException` to be thrown there. And it does occur quite rarely and quite randomly in my tests. Do you always see the same behavior?  I'm going to spend some more time digging deeper on this matter.

**Comment by kachayev** [comment]
@ztellman Zach, that's the question to you:

Right now `aleph.netty/wrap-future` creates an intermediate deferred passing `nil` as an executor. [Here](https://github.com/ztellman/aleph/blob/9f886bdb15598cbcc64763e9a9e1e93b06958c7b/src/aleph/netty.clj#L196). The change was "quietly" introduced with this [commit](https://github.com/ztellman/aleph/commit/0f45a5bbaca624e190538c786ce33514f6c3d2e6). Was that intentional?

**Comment by kachayev** [comment]
@petterik Would you please run your tests with the latest changes I've pushed to this branch? I'm super curious.

**Comment by petterik** [comment]
@kachayev There's quite a large number of tests and I did see errors happening every time I ran the test suite. I don't know, however, whether they happen in the same order nor if it's it was the same exact tests that caused these errors.

**Comment by petterik** [comment]
@kachayev Yes! Will do. Btw, to be clear, I did not get any test errors with this branch earlier, as I wrote here: https://github.com/ztellman/aleph/pull/406#issuecomment-430059912

**Comment by kachayev** [comment]
@petterik Thanks in advance!

**Comment by petterik** [comment]
@kachayev Looking good! 👍

Ran our test suite 3 times and got no errors using a jar built from your commit:
```
commit 32d66378db2845cbce4de44015ba94026350d4bb (HEAD, kachayev/ft-gracefull-shutdown)
Author: Alexey Kachayev <kachayev@gmail.com>
Date:   Thu Nov 1 18:30:06 2018 +0100

    [WIP] Just an experiment to double check that wrap-future is the root of the problem
```

**Comment by kachayev** [comment]
@petterik Well... on the one hand, that's a really good news. On the other hand, it doesn't make me feel better as I've just avoided calling the function that caused the problem w/ no proper understanding of what the problem was actually about. Could work for now, but not a really sustainable for long running future. So I'm going to leave this solution as a default implementation for now (as it's way better than previous) while still looking for a real root of the problem.

**Comment by kachayev** [comment]
@petterik One another question here: do you experience any issues with leak detector when running your tests? It would not force aleph to fail in any way, it will be just printed into the log (if appropriate leak detection level was set).

**Comment by kachayev** [comment]
Okay... finally I found the cause of the problem and the proper solution for it. @petterik would you please check with your tests suite? Looking forward to hearing the feedback :)

**Comment by kachayev** [comment]
Okay... finally I found what causes the problem. And the proper solution for that. @petterik  would you please run the latest version through your tests suite? I would love to hear your feedback!

**Comment by petterik** [comment]
Just ran my test suite with `b5dd386` and it passes! I totally missed the question you asked earlier, sorry about that.

I'm impressed you found that root cause explained in #425! 👏

**Comment by kachayev** [comment]
@petterik Thanks!

**Comment by kachayev** [comment]
After carefully reviewing this PR (again), I'm going to close this. Overall, the change seems subtle but it might have negative runtime implications (e.g. performance, GC or unpredictable timeouts). Such a fundamental functionality requires careful prod-environment testing which I don't have access to right now. If anyone wants to pick up the branch to do further research/testing, I would be more than happy to provide guidance/explanations.

The only part of this effort that I would love to keep is, in fact, fixed initializer exception in listeners. But it was already back-ported into `master` branch earlier.

**Pull request closed without merging**
