### PR TITLE
Catch FileNotFoundException when sending file body

### LINKED ISSUE #459: An attempt to send non-existing file as a server response hangs up the connection
Assume the following:

```clojure
(require '[aleph.http :as http])
(def f (java.io.File. "this-file-does-not-exists"))
(http/start-server (fn [_] {:status 200 :body f}) {:port 2018})
```

Any request to the server never completes (client will hang up either until own timeout or forever).  We need to catch exceptions thrown by `RandomAccessFile` constructor [here](https://github.com/ztellman/aleph/blob/be1ee04c130660ce69ee7c6603132b36be79ec1f/src/aleph/http/core.clj#L348-L360) and respond with 500 status code.

### PR DESCRIPTION
**Pull request by kachayev**
Fixes #459.

In general, we need to be more careful with the cleanup procedure and any time `send-message` failed for whatever **uncaught** reason close the connection. This specific just PR covers one of the obvious failures that the user might face. /cc #457.

### CODE REVIEW

**Comment by ztellman** [comment]
In general, I dislike the practice of the framework surfacing an exception to the client.  If the application developer wants to do that, fine, but elsewhere we provide a bare 500 response and log the issue.  I think I'd like to mirror that here.

**Comment by kachayev** [comment]
@ztellman Do you mean how `error-response` is implemented with stack trace printer? I just copied that from the previous implementation, but yeah... sure, that might be reworked.

**Comment by kachayev** [comment]
But let's finish with #485 first, these 2 have a lot of overlapping changes.

**Comment by ztellman** [comment]
Sorry if I misattributed where that code came from, but even if I was the one that originally did it, I think it's a mistake.

**Comment by kachayev** [comment]
@ztellman Oh, no problem with that. I just think that in such a case it makes sense to implement new behavior in a separated PR not to mess up the history of changes. WDYT?

**Comment by kachayev** [comment]
@ztellman Merged with the latest master changes (notably `http-file` functionality). I also made internal server error to look just the same for any exception that happened. WDYT?

**Pull request merged**
